# Generated by Django 3.0.4 on 2020-04-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('nsfw', models.BooleanField()),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
